#!/bin/bash

FALLBACK_VERSION="0.18.3"

if [ "$1" != "" ]; then
    VERSION="$1"
else
    VERSION=$FALLBACK_VERSION
fi

DEBIAN_PACKAGE=bat_${VERSION}_amd64.deb

# install bat
wget https://github.com/sharkdp/bat/releases/download/v${VERSION}/$DEBIAN_PACKAGE
sudo dpkg -i $DEBIAN_PACKAGE
rm $DEBIAN_PACKAGE

echo
'"bat" has been installed'
