#!/bin/bash

SPARK_VERSION=spark-3.1.2-bin-hadoop2.7
SPARK_URL=https://archive.apache.org/dist/spark/spark-3.1.2/$SPARK_VERSION.tgz

TARGET_LOCATION="$HOME/downloads"

wget $SPARK_URL -P $TARGET_LOCATION



